# Generated by Django 6.0 on 2025-12-16 15:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pharmacy business name', max_length=200)),
                ('license_number', models.CharField(help_text='Unique pharmacy license number', max_length=50, unique=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email for the pharmacy', max_length=254, unique=True)),
                ('street_address', models.CharField(help_text='Street address of the pharmacy', max_length=255)),
                ('city', models.CharField(help_text='City where pharmacy is located', max_length=100)),
                ('state', models.CharField(help_text='State where pharmacy is located', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=10)),
                ('phone_number', models.CharField(help_text='Indian phone number in format: +91XXXXXXXXXX', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+91XXXXXXXXXX' (Indian numbers only)", regex='^\\+91\\d{10}$')])),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this pharmacy has been verified')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when pharmacy was registered')),
            ],
            options={
                'verbose_name': 'pharmacy',
                'verbose_name_plural': 'pharmacies',
                'indexes': [models.Index(fields=['license_number'], name='pharmacies__license_f09a67_idx'), models.Index(fields=['city', 'state'], name='pharmacies__city_422fe8_idx'), models.Index(fields=['is_verified'], name='pharmacies__is_veri_ca697d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(help_text='Commercial/brand name of the medicine', max_length=200)),
                ('generic_name', models.CharField(help_text='Generic/scientific name of the medicine', max_length=200)),
                ('manufacturer', models.CharField(help_text='Manufacturer of the medicine', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit (minimum 0.01)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_quantity', models.PositiveIntegerField(help_text='Current stock quantity (non-negative)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when medicine was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when medicine was last updated')),
                ('pharmacy', models.ForeignKey(help_text='Pharmacy that stocks this medicine', on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'medicine',
                'verbose_name_plural': 'medicines',
                'indexes': [models.Index(fields=['commercial_name'], name='pharmacies__commerc_e32168_idx'), models.Index(fields=['generic_name'], name='pharmacies__generic_de6704_idx'), models.Index(fields=['manufacturer'], name='pharmacies__manufac_06a22b_idx'), models.Index(fields=['pharmacy', 'stock_quantity'], name='pharmacies__pharmac_4cc62f_idx')],
                'constraints': [models.UniqueConstraint(fields=('commercial_name', 'pharmacy'), name='unique_medicine_per_pharmacy')],
            },
        ),
    ]
