# Generated by Django 6.0 on 2025-12-16 16:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for the order (minimum 0.01)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='placed', help_text='Current order status', max_length=20)),
                ('payment_reference_id', models.CharField(blank=True, help_text='Payment reference ID from payment gateway', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when order was created')),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping tracking number', max_length=100)),
                ('patient', models.ForeignKey(help_text='Patient who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(help_text='Pharmacy fulfilling this order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pharmacies.pharmacy')),
                ('prescription', models.ForeignKey(help_text='Prescription for this order (must be verified)', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered (minimum 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of order (minimum 0.01)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('medicine', models.ForeignKey(help_text='Medicine being ordered', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='pharmacies.medicine')),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['patient'], name='orders_orde_patient_1eb610_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pharmacy'], name='orders_orde_pharmac_e6040d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['prescription'], name='orders_orde_prescri_c26507_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
    ]
