# Generated by Django 6.0 on 2025-12-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, help_text='Use set_password() method to set password', max_length=128, verbose_name='password'),
        ),
    ]
