# Generated by Django 6.0 on 2025-12-16 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_image_path', models.CharField(help_text='S3 path to prescription image file', max_length=500)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_verification', help_text='Current verification status', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when prescription was uploaded')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when prescription was verified or rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (required when status is rejected)')),
                ('patient', models.ForeignKey(help_text='Patient who uploaded this prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(blank=True, help_text='Pharmacy admin who verified or rejected this prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['patient'], name='prescriptio_patient_eeec74_idx'), models.Index(fields=['status'], name='prescriptio_status_940ca9_idx')],
            },
        ),
    ]
